# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bowtie2=2.5.4
  - conda-forge::gcc=15.2.0
  - conda-forge::gxx=15.2.0
  - conda-forge::wget=1.25.0